name: Generate File Hash

on:
  push:
    branches: [ main ]
    paths:
      - 'index.html'
  workflow_dispatch:

jobs:
  generate-hash:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Generate SHA-256 hash
      id: hash
      run: |
        HASH=$(sha256sum index.html | cut -d' ' -f1)
        echo "SHA256_HASH=$HASH" >> $GITHUB_ENV
        echo "::notice title=File Hash::SHA-256: $HASH"
        
    - name: Create hash file
      run: |
        echo "# Code Integrity Hashes" > INTEGRITY.md
        echo "" >> INTEGRITY.md
        echo "Generated at: $(date -u '+%Y-%m-%d %H:%M:%S UTC')" >> INTEGRITY.md
        echo "" >> INTEGRITY.md
        echo "## index.html" >> INTEGRITY.md
        echo "- SHA-256: \`$SHA256_HASH\`" >> INTEGRITY.md
        echo "- Commit: ${{ github.sha }}" >> INTEGRITY.md
        echo "- Branch: ${{ github.ref_name }}" >> INTEGRITY.md
        echo "" >> INTEGRITY.md
        echo "## Verification" >> INTEGRITY.md
        echo "To verify the integrity of the deployed code:" >> INTEGRITY.md
        echo "1. Open the developer console (F12)" >> INTEGRITY.md
        echo "2. Run: \`debugApp.verifyIntegrity()\`" >> INTEGRITY.md
        echo "3. Compare the displayed hash with the one above" >> INTEGRITY.md
        
    - name: Update README with hash
      run: |
        # Check if Integrity section exists
        if grep -q "## Code Integrity" README.md; then
          # Update existing section
          sed -i '/## Code Integrity/,/^##[^#]/{//!d}' README.md
          sed -i '/## Code Integrity/a\\n- Current SHA-256: `'"$SHA256_HASH"'`\n- Last verified: '"$(date -u '+%Y-%m-%d %H:%M UTC')"'\n- Commit: `'"${GITHUB_SHA:0:7}"'`\n' README.md
        else
          # Add new section
          echo "" >> README.md
          echo "## Code Integrity" >> README.md
          echo "" >> README.md
          echo "- Current SHA-256: \`$SHA256_HASH\`" >> README.md
          echo "- Last verified: $(date -u '+%Y-%m-%d %H:%M UTC')" >> README.md
          echo "- Commit: \`${GITHUB_SHA:0:7}\`" >> README.md
        fi
        
    - name: Commit hash files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add INTEGRITY.md README.md
        git diff --staged --quiet || git commit -m "Update integrity hashes [skip ci]"
        git push || echo "No changes to push"